# This is a sample makefile for a source code directory
# Copy this as Makefile to all directories that contains source code
# 

# All global settings are here
# Use absolute or relative path
include ../../defs.mak

# Put here anything that is related to _this_ directory only.
# Note that $(prefix) is now the absolute path to topdir.

# For example:
#deps += conf.h
#includes += -I$(prefix)/hardware 
#defines += -Dhwver2



# this rule makes .o files from all sources in this directory

all:  $(objects)
	@echo $(objects)
	

# The rest of rules are here
include ../../rules.mak

	 
      
      
