# This is a copy of Makefile.subdir

# All global settings are here
# Use absolute or relative path
include ../defs.mak

# Put here anything that is related to this directory only.
# Note that $(prefix) is now the absolute path to topdir.

# For example:
#deps += conf.h
#includes += -I$(prefix)/hardware 
#defines += -Dhwver2

includes += -Idrv

# this rule makes .o files from all sources in this directory

all:  $(objects)
	@echo $(objects)
	

# The rest of rules are here
include ../rules.mak

	 
      
      
